### ISSUE TITLE
Calendar/Schedule access

### ISSUE THREAD

**Issue by 6t9camaro** [bdunn44/hass-jellyfish-lighting#28]
Any possibility of adding the ability to add items to the JF Schedule?

Would love the ability to easily add schedule events to the calendar, using Home Assistant and a calendar interface. This would make it much easier to schedule things such as 'Sporting Event" lighting, since there are other Add-ins that provide dates/times for those events. This could also open up the possibility to do things like "October 1-31" randomize all of the JF lighting schemes that have Halloween in their name and add them to the schedule.

**Comment by usingapc** [comment]
I use the built in calendar function in home assistant for this function.
It is significantly easier than messing with the calendar in JF imo.

**Comment by 6t9camaro** [comment]
@usingapc Can you explain how? I'm not seeing a way to do this....

**Comment by usingapc** [comment]
You can add a [Local Calendar](https://www.home-assistant.io/integrations/local_calendar) as an integration.  In the calendar I created all day events on days when I want a specific effect to run.  

Then I created an Automation that uses If/Then building blocks to check the calendar for an all day event and run the corresponding effects.  If no event is in the calendar, it does my normal night effects that I created.  Here is the YAML for my Automation to turn them on(I use a separate automation to turn them off):

```
alias: Front House Night Lights On
description: ""
mode: single
triggers:
  - event: sunset
    offset: "-00:10:00"
    trigger: sun
  - entity_id:
      - light.front_yard_can_lights
    to: "on"
    trigger: state
conditions: []
actions:
  - if:
      - condition: state
        entity_id: calendar.jellyfish_lighting
        state: "off"
    then:
      - data: {}
        target:
          entity_id: input_boolean.jellyfish_lighting_normal_accent_switch
        action: homeassistant.turn_on
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Easter
    then:
      - data:
          effect: Spring/Easter Two
        target:
          entity_id: light.jellyfish_lighting_all_zones
        action: light.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: MemorialDay
    then:
      - data:
          effect: Holidays/Independence Paint
        target:
          entity_id: light.jellyfish_lighting_all_zones
        action: light.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: IndependenceDay
    then:
      - data:
          effect: Holidays/Independence Paint
        target:
          entity_id: light.jellyfish_lighting_all_zones
        action: light.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Halloween
    then:
      - data: {}
        target:
          entity_id: script.jellyfish_lighting_halloween
        action: homeassistant.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Thanksgiving
    then:
      - data:
          effect: Holidays/Thanksgiving
        target:
          entity_id: light.jellyfish_lighting_all_zones
        action: light.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Christmas1
    then:
      - data: {}
        target:
          entity_id: script.jellyfish_lighting_christmas_scene_1
        action: homeassistant.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Christmas2
    then:
      - data: {}
        target:
          entity_id: script.jellyfish_lighting_christmas_scene_2
        action: homeassistant.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Christmas3
    then:
      - data: {}
        target:
          entity_id: script.jellyfish_lighting_christmas_scene_3
        action: homeassistant.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Christmas4
    then:
      - data: {}
        target:
          entity_id: script.jellyfish_lighting_christmas_scene_4
        action: homeassistant.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Christmas5
    then:
      - data: {}
        target:
          entity_id: script.jellyfish_lighting_christmas_scene_5
        action: homeassistant.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Christmas6
    then:
      - data: {}
        target:
          entity_id: script.jellyfish_lighting_christmas_scene_6
        action: homeassistant.turn_on
    enabled: true
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Christmas7
    then:
      - data: {}
        target:
          entity_id: script.jellyfish_lighting_christmas_scene_7
        action: homeassistant.turn_on
    enabled: true
    else: []
  - if:
      - condition: and
        conditions:
          - condition: state
            entity_id: calendar.jellyfish_lighting
            state: "on"
          - condition: state
            entity_id: calendar.jellyfish_lighting
            attribute: message
            state: Christmas8
    then:
      - data: {}
        target:
          entity_id: script.jellyfish_lighting_christmas_scene_8
        action: homeassistant.turn_on
    enabled: true
    else: []
  - data:
      kelvin: 4032
      brightness_pct: 80
    target:
      entity_id: light.front_yard_can_lights
    action: light.turn_on
  - data:
      brightness_pct: 80
      kelvin: 6050
    target:
      entity_id: light.front_yard
    enabled: false
    action: light.turn_on

```

**Comment by 6t9camaro** [comment]
Awesome info! Thank you, I'll give it a go this evening!

**Comment by bdunn44** [comment]
For what it's worth I do something very similar for my light automatons but instead of the HA calendar I have the events set up in Google calendar because that's what the family uses. There's a nice Google calendar integration that syncs the calendars with HA

**Comment by 6t9camaro** [comment]
Thank you both!

**Comment by 6t9camaro** [comment]
Thanks to your inspiration here is the solution I came up with...
On the Calendar you just need to enter the 'Holiday' as the message in the calendar, a string that matches the JF Holidays, such as the 'Halloween' portion of  Halloween/Spooky. Then the Automation + Script will randomize all of the 'Halloween' entries from JF and pick one.
If you want a specific effect for a specific day then you can enter the Holiday like above and then enter the effect as the Description in the calendar and that is the effect that will be used.

Automation:
```
alias: Jellyfish Calendar Automation
description: ""
triggers:
  - event: sunset
    offset: "-00:10:00"
    trigger: sun
    enabled: true
  - entity_id:
      - light.front_porch_2
    to: "on"
    trigger: state
conditions:
  - condition: state
    entity_id: input_boolean.jellyfish_calendar_disable
    state: "off"
actions:
  - if:
      - condition: state
        entity_id: calendar.jellyfish_lighting
        state: "off"
    then:
      - action: light.turn_on
        target:
          entity_id:
            - light.all_jellyfish_lights
        data:
          effect: Colors/hilight
    else:
      - action: script.jf_effect_selector
        data: {}
        response_variable: effect
      - action: light.turn_on
        metadata: {}
        data:
          effect: |
            {{ effect['value'] | string }}  
        target:
          entity_id: light.all_jellyfish_lights
mode: single
```

Script:
```alias: JF Effect Selector
variables:
  selected_effect: >
    {% set ns = namespace(effects = []) %} {%- if
    state_attr('calendar.jellyfish_lighting', 'description') -%}
      {%- set effect = state_attr('calendar.jellyfish_lighting', 'message') + '/' + state_attr('calendar.jellyfish_lighting', 'description') -%}
    {%- else -%}
      {% for item in states.light.jf_family.attributes.effect_list -%}
        {%- set category = item.split('/') -%}
        {%- if category[0] == state_attr('calendar.jellyfish_lighting', 'message') -%} 
          {%- set ns.effects = ns.effects + [item] -%}
        {%- endif -%}
      {%- endfor -%}
      {% set effect = (ns.effects | random) %}
    {%- endif -%} {{ {'value': effect} }}
sequence:
  - stop: End
    response_variable: selected_effect
description: Select a random effect based on Calendar holiday
```
